-- UNTESTED
SELECT 
    'CREATE TABLE ' || TABLE_NAME || ' (' || CHR(10) ||
    LISTAGG(
        COLUMN_NAME || ' ' || 
        DATA_TYPE || 
        CASE 
            WHEN DATA_TYPE IN ('CHAR', 'VARCHAR2') THEN '(' || DATA_LENGTH || ')'
            WHEN DATA_TYPE IN ('NUMBER') THEN 
                CASE WHEN DATA_PRECISION IS NULL THEN ''
                    ELSE '(' || DATA_PRECISION || 
                        CASE WHEN DATA_SCALE > 0 THEN ',' || DATA_SCALE END || ')'
                END
            ELSE ''
        END ||
        CASE WHEN NULLABLE = 'N' THEN ' NOT NULL' END
    , ',' || CHR(10)) WITHIN GROUP (ORDER BY COLUMN_ID) || CHR(10) || ');' AS SQLText
FROM ALL_TAB_COLUMNS
WHERE OWNER = USER
  AND TABLE_NAME NOT IN ('SPT_FALLBACK_DB', 'SPT_FALLBACK_DEV', 'SPT_FALLBACK_USG', 'SPT_MONITOR', 'SPT_VALUES')
GROUP BY TABLE_NAME

UNION ALL

SELECT 
    'INSERT INTO ' || TABLE_NAME || ' (' ||
    LISTAGG(COLUMN_NAME, ', ') WITHIN GROUP (ORDER BY COLUMN_ID) ||
    ') SELECT ' ||
    LISTAGG(COLUMN_NAME, ', ') WITHIN GROUP (ORDER BY COLUMN_ID) ||
    ' FROM ' || TABLE_NAME || ';' AS SQLText
FROM ALL_TAB_COLUMNS
WHERE OWNER = USER
  AND TABLE_NAME NOT IN ('SPT_FALLBACK_DB', 'SPT_FALLBACK_DEV', 'SPT_FALLBACK_USG', 'SPT_MONITOR', 'SPT_VALUES')
GROUP BY TABLE_NAME;
